apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-lambda
  title: Create a Python lambda app
  description: A template to create a new Python app
  tags:
    - python
    - lambda
spec:
  owner: Field_Engineering
  type: service
  parameters:
    - title: Python Lambda app details
      required:
        - project_name
      properties:
        project_name:
          title: Name of your new app
          type: string
          description: Unique name of the app (will also be name of the repository)
    - title: Service Infrastructure Details
      required:
        - owner
      properties:
        cloud_provider:
          title: Choose a cloud provider for Deployment
          type: string
          enum: ["GCP", "AWS"]
          default: GCP
        owner:
          title: Choose an Owner for the Service
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        # This field is hidden but needed to authenticate the request to trigger the pipeline
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Creating your python app
      action: trigger:harness-custom-pipeline
      input:
        url: "https://app.harness.io/ng/account/6_vVHzo9Qeu9fXvj-AcbCQ/module/cd/orgs/SE_Sandbox/projects/Capital_One_IDP_Demo/pipelines/E2E_Onboarding/pipeline-studio?storeType=INLINE"
        inputset:
          project_name: ${{ parameters.project_name }}
        apikey: ${{ parameters.token }}

  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
